### ISSUE TITLE
Cannot advance past Chapter 2, challenge 1 

### ISSUE THREAD

**Issue by adamjonas** [saving-satoshi/saving-satoshi#677] opened 2023-10-10 00:43 UTC
https://github.com/saving-satoshi/saving-satoshi/assets/755825/85ecb6b9-4567-419a-b397-c63bc9635693

**Comment by benalleng** [comment] 2023-10-10 13:26
I can't reproduce this bug

**Comment by adamjonas** [comment] 2023-10-19 20:34
Same issue:

https://github.com/saving-satoshi/saving-satoshi/assets/755825/98ef0956-d8bd-459c-a3f4-c58a245764ae

**Comment by adamjonas** [comment] 2023-10-19 20:36
Both of these are with pre-existing accounts where I went back to a previous lesson. I didn't run into this when I did it from scratch in a incognito browser.

**Comment by benalleng** [comment] 2023-10-19 20:42
is this screen-refresh behavior happening automatically?

**Comment by benalleng** [comment] 2023-10-19 20:49
I also see that the progress lock is in the navBar in the top-right of your screen. Have these accounts completed all the chapters?

**Comment by aassoiants** [comment] 2023-10-22 23:12
I've had something like this happen today on Chap 2 Challenge 2 (see image). 

I wrote the right answer, it refreshed super briefly, then brought me to the same page. 

I got past it by trying again a few times and hopping out and into the navigation chapter/ challenge navigation

![image](https://github.com/saving-satoshi/saving-satoshi/assets/126297088/6a16d418-b598-4ce0-a0be-623d0c6f9c3e)

**Comment by benalleng** [comment] 2024-03-18 21:11
I believe that this behavior has been fixed as of #846

**Closed by benalleng** 2024-03-18 21:11 UTC
Labels: bug
