### ISSUE TITLE
Some translations lag behind the rest of the page or are missing

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#250] opened 2023-03-08 21:18 UTC
I am only able to reproduce this occasionally, It sometimes takes a single refresh but other times fully reloading the page `Ctrl + Shift + R`. Some of the translations are not rendered with the rest of the translation strings despite them all being in the same `translations.ts` file.

These 2 below screenshots are 2 refreshes apart. 

![image](https://user-images.githubusercontent.com/108441023/223851673-11bb0b3f-4bc6-4cb5-a829-96864cf84ff3.png)

![image](https://user-images.githubusercontent.com/108441023/223851742-c78d640b-c454-41f8-88aa-80e9eaf8cbd4.png)

**Comment by afterburn** [comment] 2023-03-08 21:39
I can reproduce this too:
1. I set my default locale to English.
2. I go to www.savingsatoshi.com/nl to force Dutch even though my default locale is set to English.
3. I then click on "Start the demo", takes me to /en/chapters.
4. I see mixed Dutch & English translations.

I think this might have something to do with hydration / mixed use of Server & Client components in combination with our `useLang` hook. I created it because the alternative is to prop drill `params.lang` all the way from the page down to the component, where you use it for `useTranslations`, but that approach might be a fix for this issue (not 100% sure though).

Do you actually run into this issue if you don't change your locale & just go through the pages naturally? If not, we can maybe leave this for now until we have the language switcher (#148). Once we have that we'll probably see this issue more often.

**Comment by benalleng** [comment] 2023-03-08 21:48
If i set my locale to English in my browser settings and close or hard refresh my browser it appears to go through the website without having any incorrect translations. However, 1-in-5 times, or rarer, the `chapter_one.paragraph_one` `chapter_one.paragraph_two` `chapter_one.paragraph_three` are still in the Dutch translation

**Comment by benalleng** [comment] 2023-03-08 21:52
It seems to happen more often on the first run-through after browser refresh or opening a fresh incognito window

**Comment by benalleng** [comment] 2023-03-08 23:20
I am going to also do some further testing also it could be that I have something cached or some other problem. In the most recent preview of #248 i could no longer reproduce it. If I can't reliably reproduce it moving forward I will close this

**Comment by ecurrencyhodler** [comment] 2023-03-08 23:29
I am able to reliably reproduce the issue. I created this in regular mode in chrome as well as in incognito mode. I get this result both times.

If you see on the bottom right is dutch translations even though the url has /en. My default language from chrome is also english.

https://user-images.githubusercontent.com/32662508/223875873-9b60c8f5-32f7-49ac-acb7-ec2e38aed6c5.mov

Also as a separate issue, sometimes I get flashed a white screen when I refresh the page. I'm unable to reliably reproduce this though. I'll create a separate issue for it.

https://user-images.githubusercontent.com/32662508/223876161-47abbe6e-1c81-40be-a974-1d5536cda3c5.mov

**Comment by ecurrencyhodler** [comment] 2023-03-08 23:32
I also reproduced this in mobile chrome.  https://user-images.githubusercontent.com/32662508/223876580-0a6f98a3-6112-4f93-b5fa-2cb9a7c70aaf.MOV

**Comment by ecurrencyhodler** [comment] 2023-03-08 23:39
I am no longer able to reproduce this in incognito. But I consistently and reliable get results when I force the url /nl and refresh the page. It shows a mix of dutch + english.

**Comment by ecurrencyhodler** [comment] 2023-03-09 17:36
Assigned this to v1 as the demo is not focusing on internationalization.

**Comment by benalleng** [comment] 2023-03-17 20:00
same question as #256
> With the addition of some new logic in translations.ts I was wondering if this is still an issue, granted we are still dealing with links always switching to the /en locale but i wanted to ask if anyone could reliably reproduce this particular bug anymore?

Even when forcing the page to load the `/nl` translations I cannot ever bring about this bug anymore with the current `translations.ts` logic

**Comment by ecurrencyhodler** [comment] 2023-03-17 20:02
I can no longer repro.

**Comment by benalleng** [comment] 2023-03-17 20:05
Same thought for this issue as #256. I think we should close

**Comment by ecurrencyhodler** [comment] 2023-03-17 20:05
Closing

**Closed by ecurrencyhodler** 2023-03-17 20:05 UTC
Labels: bug
