### ISSUE TITLE
Help with translation into Russian.

### ISSUE THREAD

**Issue by ArtoymKryazhev** [saving-satoshi/saving-satoshi#1157] opened 2024-11-03 20:17 UTC
Hello. I am from Russia. My name is Artem and I am 19. I came across your game in one of the Russian Telegram channels. I would like to offer you my help with translation into Russian. Exclusively in a voluntary form.

**Comment by benalleng** [comment] 2024-11-04 18:27
Thats great! feel free to check out the translating README https://github.com/saving-satoshi/saving-satoshi/blob/dev/i18n/README.md and let us know if you have any other questions in our bitcoin design discord

**Comment by satsie** [comment] 2024-11-05 18:46
Amazing!! Thank you so much for you interest in helping with this! Tagging @aassoiants in case he can be helpful for review :smile:

**Comment by aassoiants** [comment] 2024-11-07 04:33
@satsie ha! My proofreading would need some proofreading!

**Comment by satsie** [comment] 2024-11-22 18:36
This issue is a duplicate of https://github.com/saving-satoshi/saving-satoshi/issues/1194 so I am closing this one!

**Closed by satsie** 2024-11-22 18:36 UTC
